/* Config Sample
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 *
 * You can use environment variables using a `config.js.template` file instead of `config.js`
 * which will be converted to `config.js` while starting. For more information
 * see https://docs.magicmirror.builders/configuration/introduction.html#enviromnent-variables
 */
let config = {
	address: "0.0.0.0",	// Listen on all interfaces (was "localhost"). Allows the tablet
							// to load the page over the hotspot. Originally:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/",	// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
									// you must set the sub path here. basePath must end with a /
	ipWhitelist: [],	// Allow all clients (originally loopback only). Set [] to allow all IP addresses
									// or add a specific IPv4 of 192.168.1.5 :
									// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
									// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
									// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false,			// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "",	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "",	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",   // this variable is provided as a consistent location
			   // it is currently only used by 3rd party modules. no MagicMirror code uses this value
			   // as we have no usage, we  have no constraints on what this field holds
			   // see https://en.wikipedia.org/wiki/Locale_(computer_software) for the possibilities

	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",

	modules: [
		// {
		// 	module: "alert",
		// },
		// {
		// 	module: "updatenotification",
		// 	position: "top_bar"
		// },
		{
			module: "clock",
			position: "top_center",
			displaySeconds: false
		},
		{
			module: "MMM-SensorUI",
			position: "top_center"
		},
		{
			module: "MMM-VidConf",
			position: "top_center"
		},
		{
			module: "MMM-CustomMQTTBridge",
			// position: "top_right",
			/*
			 * RMMS broker config — set caFile/certFile/keyFile to absolute
			 * paths to the mirror bundle generated by scripts/provision_ca.sh
			 * (out/mirror-<id>/). For Yasmina's old plaintext localhost demo,
			 * set broker to "mqtt://localhost:1883" and leave the three file
			 * paths empty.
			 */
			config: {
				broker:   "mqtts://172.20.10.12:8883",
				clientId: "mirror-de4ed19a",
				caFile:   process.env.HOME + "/projects/BEP-Remote-Health-Monitoring-System-for-the-Elderly/out/mirror-de4ed19a/ca.crt",
				certFile: process.env.HOME + "/projects/BEP-Remote-Health-Monitoring-System-for-the-Elderly/out/mirror-de4ed19a/cert.pem",
				keyFile:  process.env.HOME + "/projects/BEP-Remote-Health-Monitoring-System-for-the-Elderly/out/mirror-de4ed19a/key.pem",
				topics:   ["rmms/+/+"]
			}
		},
	    {
			module: "MMM-pages",
			config: {
				timings: {
					default: 5000,               // rotate every 5 seconds
					0: 20000,                    // page 0 rotates every 20 seconds
					"admin": 30000               // admin hidden page auto-returns after 30 seconds
				},
				modules: [
					["MMM-SensorUI"], // page 0
					["MMM-VidConf"],  // page 1
				],
				fixed: [                         // modules that are always shown
					"clock",

					// "MMM-page-indicator"
				],
				// hiddenPages: {                   // modules that are only shown on specific pages
				// 	"screenSaver": [
				// 		"clock",
				// 		"MMM-BackgroundSlideshow"
				// 	],
				// 	"admin": [
				// 		"MMM-SystemMonitor",
				// 		"MMM-OnScreenMenu"
				// 	]
				// }
			}
		},
		// {
		// 	module: 'MMM-Template',
		// 	position: 'lower_third',
		// 	config: {
		// 		exampleContent: 'Welcome world'
		// 	}
    	// },
		// {
		// 	module: "calendar",
		// 	header: "US Holidays",
		// 	position: "top_left",
		// 	config: {
		// 		calendars: [
		// 			{
		// 				fetchInterval: 7 * 24 * 60 * 60 * 1000,
		// 				symbol: "calendar-check",
		// 				url: "https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics"
		// 			}
		// 		]
		// 	}
		// },
		// {
		// 	module: "compliments",
		// 	position: "lower_third"
		// },
		// {
		// 	module: "weather",
		// 	position: "top_right",
		// 	config: {
		// 		weatherProvider: "openmeteo",
		// 		type: "current",
		// 		lat: 40.776676,
		// 		lon: -73.971321
		// 	}
		// },
		// {
		// 	module: "weather",
		// 	position: "top_right",
		// 	header: "Weather Forecast",
		// 	config: {
		// 		weatherProvider: "openmeteo",
		// 		type: "forecast",
		// 		lat: 40.776676,
		// 		lon: -73.971321
		// 	}
		// },
		// {
		// 	module: "newsfeed",
		// 	position: "bottom_bar",
		// 	config: {
		// 		feeds: [
		// 			{
		// 				title: "New York Times",
		// 				url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
		// 			}
		// 		],
		// 		showSourceTitle: true,
		// 		showPublishDate: true,
		// 		broadcastNewsFeeds: true,
		// 		broadcastNewsUpdates: true
		// 	}
		// },
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }
