#!/usr/bin/env python3
"""Build-time helper for the bringup_mqtt UF2.

Reads a device-provisioning bundle produced by scripts/provision_ca.sh and
emits a C header containing the CA cert, device cert, device key, and UUID as
compile-time constants. Invoked from test/bringup/CMakeLists.txt; not used by
the production firmware (which loads these from littlefs).

Usage:
    bake_certs.py <bundle-dir> <out-header>
"""
import json
import sys
from pathlib import Path


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        out.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.write("};\n")
    out.write(f"static const unsigned int {name}_len = {len(data)};\n\n")


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: bake_certs.py <bundle-dir> <out-header>\n")
        return 2
    bundle = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    ca = (bundle / "ca.der").read_bytes()
    crt = (bundle / "dev.crt").read_bytes()
    key = (bundle / "dev.key").read_bytes()
    uuid = json.loads((bundle / "device.json").read_text())["uuid"]

    with out_path.open("w") as f:
        f.write("/* AUTO-GENERATED by scripts/bake_certs.py — do not edit. */\n")
        f.write("#pragma once\n\n")
        emit_array(f, "rmms_ca_der", ca)
        emit_array(f, "rmms_dev_crt", crt)
        emit_array(f, "rmms_dev_key", key)
        f.write(f'#define RMMS_DEVICE_UUID "{uuid}"\n')

    return 0


if __name__ == "__main__":
    sys.exit(main())
